testingmode: false
graceful_timeout: "15s"
log.level: "info"
log.json: false
http.address: "0.0.0.0:8080"
http.compress: false
http.idle_timeout: "15s"
http.write_timeout: "15s"
http.read_timeout: "15s"
auth_client.library_url: "https://keycloak.service/auth/js/keycloak.js"
auth_client.public_keys_url: "http://localhost:8080/auth/realms/demoRealm/protocol/openid-connect/certs"
